- .github/workflows/server-ci.yml
- cn-lsp/client/README.md
- cn-lsp/client/package-lock.json
- cn-lsp/client/package.json
- cn-lsp/client/src/extension.ts
- cn-lsp/server/README.md
- cn-lsp/server/cnlsp.opam.locked-4.14.1
- cn-lsp/server/cnlsp.opam.locked-5.1.1
Using switches makes the process a bit less fiddly and error-prone, and should obviate some of the stale dependency issues the previous process entailed.
> CN server: use local switches for installation instructions and in CI

- cn-client/README.md
- cn-client/package.json
- cn-lsp.opam
- cn-lsp/lib/dune
- cn-lsp/lib/server.ml
- cn-lsp/lib/serverTelemetry.ml
- dune-project
In furtherance of #125, this implements generation and serialization of timestamped telemetry events for several key points in the server/verification lifecycle, mentioned in that issue:
- Server startup
- Server shutdown
- File open
- File close
- Beginning of verification attempt
- End of verification, including outcome
It also updates the client to allow a user to choose whether to collect and where to store telemetry. This collection is disabled by default.
This leaves some aspects of #125 unimplemented:
1. Generation/collection and serialization of user profile information (e.g. user identifiers, expertise levels)
2. Recording telemetry on {re,}configuration of client/server preferences
3. Determining and ascribing task identifiers to telemetry events
There are no technical blockers …
> client, server: record basic telemetry events

- cn-client/package.json
- cn-lsp/lib/server.ml
In particular, offer users the option to associate a custom (string) identifier with the telemetry they generate. This option appears in the extension's settings, alongside the choice of whether to collect/where to store telemetry.
If we need more complex identifiers than strings, this setup is extensible enough to read and store them. However, per https://github.com/GaloisInc/VERSE-Toolchain/issues/125#issuecomment-2486089899, we're hoping to avoid soliciting or storing a ton of PII here, so I've kept this minimal.
> client, server: allow associating user information with telemetry

- cn-lsp/lib/server.ml
- cn-lsp/lib/serverConfig.ml
- cn-lsp/lib/serverTelemetry.ml
Each time a user updates a configuration setting, as well as once on startup, the new configuration will be recorded in the user's telemetry.
> server: telemetry for configuration changes

- cn-lsp/lib/lspCn.ml
- cn-lsp/lib/server.ml
- cn-lsp/lib/serverTelemetry.ml
At present, telemetry events simply encode whether the event ended in success, failure, or neither. This expands the failure outcome to represent optional, additional context about the failure, and fills it with summaries of verification failures from Cerberus and CN.
This additional context is not particularly structured - it's basically the Cerberus/CN-defined pretty-printed version of the error, as a user would see in a tooltip. For example, here's how an error summary might appear in JSON-encoded telemetry:
```json
{
...
"causes": [
"/Users/sam/projects/verse/cn-tutorial/src/examples/dll/add_orig.broken.c:15:9-27: Left-over unused resource 'Owned<struct dllist*>(&call_malloc__dllist0.return->next)(NULL)'"
],
...
}
```
I don't know whether this is a sufficient substitute for …
> server: record summarized error contents in telemetry

- cn-lsp.opam
- cn-lsp.opam.locked-5.1.1
- cn-lsp.opam.template
- cn-lsp/lib/lspCerb.ml
- cn-lsp/lib/lspCn.ml
- cn-lsp/lib/verify.ml
- dune-project
Update CN to the latest commit available at press time, https://github.com/rems-project/cerberus/commit/d7d4e67fdb049dc35dc5fbd61a702d789394bf3d. Additionally, make use of the new solver-resetting interface made available via https://github.com/rems-project/cerberus/pull/833, which this update pulls in.
Fixes #142.
> server: update CN

- cn-client/README.md
- cn-client/package-lock.json
- cn-client/package.json
- cn-client/src/extension.ts
- cn-lsp/lib/lenses.ml
- cn-lsp/lib/parse.ml
- cn-lsp/lib/server.ml
- cn-lsp/lib/uri.ml
- cn-lsp/lib/verify.ml
[Code lenses](https://code.visualstudio.com/blogs/2017/02/12/code-lens-roundup) are small, clickable buttons that can appear at specific points in code. With these changes, the server will publish one such lens per function in a file, which can be used to verify only that function, instead of verifying every function in a file (and in its `#include`d dependencies).
Here's an example of how this looks in practice:
> client, server: allow verification of individual functions via code lenses

- cn-client/src/extension.ts
- cn-lsp/lib/lenses.ml
- cn-lsp/lib/parse.ml
- cn-lsp/lib/range.ml
- cn-lsp/lib/range.mli
- cn-lsp/lib/server.ml
- cn-lsp/lib/serverTelemetry.ml
- cn-lsp/test/dune
- cn-lsp/test/main.ml
- cn-lsp/test/parse.ml
When a user requests verification of an individual function, via the code lenses that #152 introduced, the server will record the name, body, and spec (if any) of that function in a telemetry event.
> server: record function names, bodies, specs in telemetry

- cn-lsp/lib/progress.ml
- cn-lsp/lib/server.ml
- cn-lsp/lib/verify.ml
With these changes, the server now leverages LSP-defined [WorkDoneProgress](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workDoneProgress)-type messages to start displaying progress when verification begins, and to stop displaying it when verification ends. This progress is displayed as indefinite - we don't e.g. report progress incrementally per function in a file.
This progress is displayed as a message in the VSCode status bar at the bottom of a window, like so:
> server: report progress during verification

- README.md
Steer users to OCaml 5.1.1 (a straggler from #146) and to use `dune` for rebuilds.
> server: update build documentation

- cn-lsp/lib/lenses.ml
- cn-lsp/lib/parse.ml
- cn-lsp/lib/server.ml
To avoid silently failing when we fail to preprocess files, as we currently do on Linux (see #157).
> server: structured error-handling for parsing, code lenses

- cn-lsp/lib/parse.ml
- cn-lsp/test/parse.ml
Fixes #157.
The issue was, seemingly, that I was invoking `cc` with `Unix.create_process "cc" [| "-std=c11"; "-E"; ... |]`, when in fact I needed to say `Unix.create_process "cc" [| "cc"; "-std=c11"; "-E"; ... |]` - that is, provide `cc` as the 0th argument. I don't know why this wasn't an issue on macOS, but I've tried this method of process-creation on a Linux VM and it seems to solve the problem.
> server: fix preprocessing arguments

- cn-lsp/lib/lenses.ml
A stopgap measure to disambiguate the function to which a lens refers, if the lens ends up in the wrong place (see #158).
> server: include function name in verification lens

- cn-lsp/lib/server.ml
- docs/tech_notes/2025-2-21-CN-telemetry-setup-guide.md
Code lens positions are calculated based on whatever version of a document is saved to disk. Currently, a document with unsaved changes that change the position of a function can have lenses that appear in the wrong place - see #158. As a temporary fix, this entirely blocks lenses from being published for documents with unsaved changes, removing that block once the document is saved.
> server: unpublish lenses for docs with unsaved changes

- cn-client/src/extension.ts
By saving a document before requesting verification of it, we can avoid spurious verification results as a consequence of #160.
> client: save before verification

- docs/tech_notes/2025-2-21-CN-telemetry-setup-guide.md
The server's README does mention this requirement, but we should call it out in the guide as well.
> docs: explicitly mention z3 requirement in telemetry setup guide

- README.md
Needed to make the plugin work.
> Add gmp as a missing dependence

- docs/cn-lsp/2025-02-27-telemetry-schema.json
- docs/cn-lsp/2025-02-27-telemetry-schema.md
This is a point-in-time description of the schema of the telemetry data that we expect to ship to Sandia. I've taken the liberty of writing this down as a machine-readable JSON schema. Let me know if we need something more human-readable - I should be able to generate something like HTML or Markdown from it.
> docs: describe current telemetry event schema and directory layout

- README.md
This should ensure that someone who's installing the language server from source will understand that they also need to install the accompanying language client.
> doc: explicitly mention client installation

- cn-client/package-lock.json
- cn-client/package.json
- cn-client/src/extension.ts
This variable was changed recently in Cerberus with https://github.com/rems-project/cerberus/commit/7d7271caa0d1c415f6c1088716627a0d0c29224d, and this change really should have been included in #185.
> client: use `CERB_INSTALL_PREFIX` to specify Cerberus runtime path

- .github/workflows/ci.yml
- cn-client/.vscodeignore
- cn-client/package-lock.json
- cn-client/package.json
- cn-client/src/extension.ts
In #191, I misunderstood the change in semantics alluded to in https://github.com/rems-project/cerberus/commit/7d7271caa0d1c415f6c1088716627a0d0c29224d. `CERB_INSTALL_PREFIX` is not meant to refer to a location like `<opam-directory>/lib/cerberus-lib/runtime`, but rather to `<opam-directory>` itself, since Cerberus will unconditionally append `/lib/cerberus-lib/runtime` to whatever path is specified.
Accommodating this also means that our CI's bundling process needs to change. Since Cerberus expects to find its runtime files at a specific path, we need to mimic `opam`'s directory structure to replicate that path.
> client: fix Cerberus runtime path specification
